import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, Compass, CheckCircle2, GitPullRequest, ShieldCheck, Flame } from 'lucide-react';
import { CuriosityGoal, EvolutionProposal, AppTheme } from '../types';
import { TabHeader } from './TabHeader';
interface AutonomyCuriosityProps { goals: CuriosityGoal[]; proposals: EvolutionProposal[]; onTriggerCuriosity: () => void; theme?: AppTheme; }
export const AutonomyCuriosity: React.FC<AutonomyCuriosityProps> = ({ goals, proposals, onTriggerCuriosity, theme = 'dark' }) => {
  const isDark = theme === 'dark'; const surface = isDark ? 'bg-[#0f141d]/80 border-white/10' : 'bg-white border-slate-200'; const inner = isDark ? 'bg-black/20 border-white/10' : 'bg-slate-50/50 border-slate-200';
  const headerControls = <><button onClick={onTriggerCuriosity} className="trace-action-btn" type="button"><Sparkles className="h-3 w-3" /> TRIGGER CYCLE</button><span className="trace-tab-control">IDLE LOOP / SANDBOXED</span></>;
  return (<section id="autonomy-curiosity-view" className={`trace-root ${isDark ? 'trace-dark' : ''} mx-auto w-full max-w-xl overflow-visible text-xs`}>
    <TabHeader icon={Sparkles} category="JARVIS / AUTONOMY" title="IDLE LEARNING" subtitle="Autonomous curiosity and controlled learning monitor" controls={headerControls} />
    <div className="trace-flow px-3 pb-3 sm:px-3.5 space-y-3"><div className="trace-flow-label text-[10px] font-semibold tracking-wider uppercase"><Compass size={12} /> ACTIVE CURIOSITY &amp; LEARNING <span>• IDLE LOOP</span></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
      {goals.map(goal => <motion.article key={goal.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className={`trace-stage ${surface}`}><div className="trace-stage-content p-2.5 space-y-2"><div className="flex items-center justify-between w-full gap-2"><div className="flex items-center gap-2 flex-1 min-w-0"><Flame className="h-3.5 w-3.5 shrink-0 text-orange-500" /><span className="min-w-0 flex-1 font-mono text-[11px] font-bold text-slate-800 dark:text-slate-100 break-words">{goal.text}</span></div><span className={`shrink-0 rounded-full border px-2 py-0.5 font-mono text-[9px] font-bold uppercase whitespace-nowrap ${goal.status === 'active' ? (isDark ? 'bg-brand-400/10 text-brand-300 border-brand-400/30' : 'bg-brand-50 text-brand-700 border-brand-200') : (isDark ? 'bg-emerald-400/10 text-emerald-300 border-emerald-400/30' : 'bg-emerald-50 text-emerald-700 border-emerald-200')}`}>{goal.status}</span></div><div className="pl-3 border-l-2 border-brand-500/30 space-y-1">{goal.progress.map((prog, idx) => <div key={idx} className="flex items-center gap-2 font-mono text-[10px] leading-normal text-slate-600 dark:text-slate-300"><CheckCircle2 className="h-3 w-3 shrink-0 text-emerald-500" /><span className="min-w-0 flex-1 break-words">{prog}</span></div>)}</div><div className="flex items-center justify-between w-full gap-2 border-t border-slate-200 dark:border-white/5 pt-1 font-mono text-[9px] text-slate-400"><span className="min-w-0 break-words">Origin: {goal.origin.toUpperCase()}</span><span className="shrink-0">Priority: {(goal.priority * 100).toFixed(0)}%</span></div></div></motion.article>)}
    </div><div className="trace-flow-label text-[10px] font-semibold tracking-wider uppercase"><GitPullRequest size={12} /> CONTROLLED EVOLUTION <span>• SANDBOXED PATCHES</span></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
      {proposals.map(evo => <article key={evo.id} className={`trace-stage ${inner}`}><div className="trace-stage-content p-2.5 space-y-2"><div className="flex items-center justify-between w-full gap-2"><span className="min-w-0 flex-1 font-mono text-[11px] font-bold capitalize text-slate-800 dark:text-slate-100 break-words">{evo.target.replace(/_/g, ' ')}</span><span className="shrink-0 rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 font-mono text-[9px] font-bold uppercase text-emerald-700 dark:border-emerald-500/20 dark:bg-emerald-500/10 dark:text-emerald-300 whitespace-nowrap">{evo.status}</span></div><p className="font-mono text-[10px] leading-normal text-slate-600 dark:text-slate-300 break-words">{evo.reason}</p><div className="flex items-center justify-between w-full gap-2 border-t border-slate-200 dark:border-white/5 pt-1 font-mono text-[9px] text-slate-400"><span className="min-w-0 break-words">Validation Score: {(evo.score * 100).toFixed(0)}%</span><span className="flex shrink-0 items-center gap-1 font-bold text-emerald-600 dark:text-emerald-400"><ShieldCheck className="h-3 w-3" /> VERIFIED</span></div></div></article>)}
    </div></div>
  </section>);
};
