import React from 'react';
import { Brain, Database, GraduationCap, Languages, Moon, Network, ShieldCheck, Sparkles, Target, TrendingDown } from 'lucide-react';
import { AppTheme, LiveStateResponse, SystemResourcesData } from '../types';
interface Props { liveState: LiveStateResponse | null; resources: SystemResourcesData | null; theme: AppTheme; }
type AnyRecord=Record<string,any>;
const text=(v:any)=>{if(v==null||v==='')return '—';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch{return String(v)}};
const ago=(v:any)=>{const n=Number(v||0);if(!n)return '—';const s=Math.max(0,(Date.now()-(n>1e12?n:n*1000))/1000);return s<60?`${Math.floor(s)}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};
function Node({label,value,icon:Icon,accent='#5b8def',theme,wide=false,compact=false}:{label:string;value:any;icon?:React.ElementType;accent?:string;theme:AppTheme;wide?:boolean;compact?:boolean}){const dark=theme==='dark',display=text(value);return <div className={`shrink-0 ${wide?'w-full':compact?'flex-1 min-w-0':'w-[152px]'} h-[58px] flex items-center gap-1.5 px-2 border rounded-lg ${dark?'bg-white/[.018] border-white/10':'bg-slate-50 border-slate-200'}`} title={display}>{Icon&&<span className="w-5 h-5 shrink-0 flex items-center justify-center rounded-md" style={{color:accent,background:`${accent}10`}}><Icon size={10}/></span>}<div className="min-w-0 flex-1"><div className="text-[7px] uppercase tracking-[.12em] text-slate-500 truncate">{label}</div><div className="mt-0.5 max-h-[32px] overflow-y-auto whitespace-pre-wrap break-words text-[10px] font-bold leading-tight" style={{color:accent}}>{display}</div></div></div>}
function Rail({title,subtitle,icon:Icon,accent,theme,children,organs=false,right}:{title:string;subtitle?:string;icon:React.ElementType;accent:string;theme:AppTheme;children:React.ReactNode;organs?:boolean;right?:React.ReactNode}){const dark=theme==='dark';return <section className={`trace-root overflow-hidden ${dark?'trace-dark':'trace-light'}`}><div className="px-3 py-2.5 sm:px-4"><div className="flex items-center gap-2 mb-2"><span className="w-5 h-5 shrink-0 flex items-center justify-center rounded-md" style={{color:accent,background:`${accent}10`}}><Icon size={10}/></span><div className="min-w-0 flex-1"><div className="text-[9px] font-bold uppercase tracking-wider truncate">{title}</div>{subtitle&&<div className="text-[7px] text-slate-500 truncate">{subtitle}</div>}</div>{right}</div><div className={organs?'overflow-x-auto overflow-y-hidden max-w-full':'w-full'}><div className={organs?'flex gap-1.5 min-w-max pb-0.5':'flex flex-wrap items-stretch gap-1.5'}>{children}</div></div></div></section>}

// Field paths below are read directly from core/runtime/state_bus.py's
// published snapshot (the exact file monitor.py polls) -- see
// StateBus.snapshot() for the authoritative key names. Previously this
// component guessed at plausible-looking key names (idle_loop,
// personal_typo_learning, metacognitive_calibration,
// cognitive_self_awareness, evolution_self_learning) that the real
// publisher never actually writes, so every one of these cards always
// rendered its fallback/zero value regardless of what the organism was
// really doing.
export function CognitiveMonitoringCards({liveState,resources,theme}:Props){
 const state:AnyRecord=liveState||{},learning:AnyRecord=state.learning||{},organs:AnyRecord=state.organs||{};
 const idleLast:AnyRecord=state.idle_last||{},idleActivity:AnyRecord[]=state.idle_activity||[];
 const consolidation:AnyRecord=state.memory_consolidation||{},consolidationResult:AnyRecord=consolidation.last_result||{};
 const native:AnyRecord=state.native_response_learning||{},nativeLastScan:AnyRecord=native.last_mine_result||{};
 const procedural:AnyRecord=state.procedural_memory||{};
 const typo:AnyRecord=state.idiolect_status||{};
 const decay:AnyRecord=state.memory_decay||{};
 const calibration:AnyRecord=state.calibration||{};
 const dep:AnyRecord=state.dependency_metrics||{},trainingStats:AnyRecord=state.training_data_stats||{};
 const evoSummary:AnyRecord=state.evolution_summary||{},evoCounts:AnyRecord=evoSummary.counts||{};
 const attachedOrgans=Object.entries(organs).filter(([,organ]:any)=>organ?.attached);
 const idleLastText=idleActivity.length===0?'No idle cycles recorded yet':idleLast.event==='IDLE_CYCLE_NOOP'?`NO-OP — ${idleLast.reason||'no pending goals'}`:`goal="${idleLast.goal||'?'}" step=${idleLast.step_index??'?'}`;
 const byKindText=Object.entries(procedural.by_kind||{}).map(([k,v])=>`${k}=${v}`).join('  ')||'(none learned yet)';
 const trainingText=trainingStats.total_examples?`${trainingStats.total_examples} examples`:'—';
 return <div className="space-y-2.5">
  <Rail title="ORGANISM HEALTH" subtitle="Heartbeat and readiness" icon={ShieldCheck} accent="#22c55e" theme={theme}><Node label="Heartbeat" value={state.heartbeat?.running?'ALIVE':'OFFLINE'} accent={state.heartbeat?.running?'#22c55e':'#ef4444'} theme={theme}/><Node label="Beats" value={state.heartbeat?.beats??0} accent="#22c55e" theme={theme}/><Node label="Idle" value={state.heartbeat?.idle?'TRUE':'FALSE'} icon={Moon} accent="#64748b" theme={theme}/><Node label="LLM ready" value={state.llm_ready?'TRUE':'FALSE'} accent="#5b8def" theme={theme}/></Rail>
  <Rail title="ORGAN ATTACHMENTS" subtitle="Attached organs · swipe horizontally" icon={ShieldCheck} accent="#22c55e" theme={theme} organs right={<span className="shrink-0 text-[8px] font-bold tracking-[.12em] text-emerald-400">{attachedOrgans.length}/{Object.keys(organs).length}</span>}>{attachedOrgans.length===0?<div className="w-[132px] h-[54px] shrink-0 flex items-center px-2 border rounded-lg border-white/10 text-[8px] text-slate-500">No attached organs</div>:attachedOrgans.map(([name,organ]:any)=><div key={name} className="w-[132px] h-[54px] shrink-0 flex items-center gap-2 px-2 border rounded-lg bg-emerald-500/[.035] border-emerald-500/15" title={`${name} · ${organ?.type||organ?.classType||'unknown'}`}><span className="w-1.5 h-1.5 shrink-0 rounded-full bg-emerald-400 animate-pulse"/><div className="min-w-0"><div className="text-[8px] font-bold truncate">{name}</div><div className="text-[7px] text-slate-500 truncate">{organ?.type||organ?.classType||'unknown'}</div><div className="text-[7px] font-bold text-emerald-400">ATTACHED · ONLINE</div></div></div>)}</Rail>
  <Rail title="BACKGROUND LEARNING QUEUE" subtitle="Autonomous learning telemetry" icon={GraduationCap} accent="#8b5cf6" theme={theme}><div className="grid w-full grid-cols-2 gap-1.5"><Node label="Pending" value={learning.pending??0} accent="#f59e0b" theme={theme} compact/><Node label="Processed" value={learning.processed??0} accent="#22c55e" theme={theme} compact/><Node label="Failed" value={learning.failed??0} accent="#ef4444" theme={theme} compact/><Node label="Succeeded" value={Math.max(0,Number(learning.processed??0)-Number(learning.failed??0))} accent="#22c55e" theme={theme} compact/></div></Rail>
  <Rail title="SYSTEM RESOURCES" subtitle="Process and model telemetry" icon={ShieldCheck} accent="#5b8def" theme={theme}><div className="grid w-full grid-cols-2 gap-1.5"><Node label="Max RSS RAM" value={`${resources?.process?.max_rss_mb??'—'} MB`} accent="#06b6d4" theme={theme} compact/><Node label="Threads" value={resources?.process?.threads??'—'} theme={theme} compact/><Node label="LLM backend" value={resources?.llm?.backend||'—'} theme={theme} compact/><Node label="Cognitive path" value={state.fallback_active?'NATIVE FIRST · LLM FALLBACK':'NATIVE FIRST'} accent="#22c55e" theme={theme} compact/></div></Rail>
  <Rail title="IDLE LOOP ACTIVITY" subtitle="Autonomous no-op cycles" icon={Moon} accent="#64748b" theme={theme}><Node label="Last cycle" value={idleLastText} theme={theme} wide/><div className="w-full grid grid-cols-2 gap-1.5"><Node label="Cycles count" value={idleActivity.length} theme={theme} compact/><Node label="Last active" value={ago(idleLast.timestamp)} theme={theme} compact/></div></Rail>
  <Rail title="MEMORY CONSOLIDATION" subtitle="Episodic → semantic · idle-time" icon={Database} accent="#06b6d4" theme={theme}><Node label="Run" value={consolidation.run_count??0} theme={theme}/><Node label="Examined" value={consolidationResult.examined??0} theme={theme}/><Node label="Candidates" value={consolidationResult.candidates??0} theme={theme}/><Node label="Promoted" value={consolidationResult.consolidated??0} accent="#22c55e" theme={theme}/></Rail>
  <Rail title="NATIVE RESPONSE LEARNING" subtitle="Zero-LLM-cost templates" icon={Sparkles} accent="#8b5cf6" theme={theme}><Node label="Templates learned" value={native.template_count??0} accent="#8b5cf6" theme={theme} compact/><Node label="LLM hits saved" value={native.total_hits??0} accent="#22c55e" theme={theme} compact/><Node label="Last scan" value={native.run_count?`candidates=${nativeLastScan.candidates_found??0} approved=${nativeLastScan.approved??0}`:'not run yet'} theme={theme} wide/></Rail>
  <Rail title="PROCEDURAL MEMORY" subtitle="Third memory type · learned habits" icon={Network} accent="#f59e0b" theme={theme}><Node label="Procedures" value={procedural.procedure_count??0} accent="#f59e0b" theme={theme} compact/><Node label="Hits" value={procedural.total_hits??0} theme={theme} compact/><Node label="By kind" value={byKindText} theme={theme} wide/></Rail>
  <Rail title="PERSONAL TYPO LEARNING" subtitle="Idiolect correction model" icon={Languages} accent="#5b8def" theme={theme}><div className="grid w-full grid-cols-3 gap-1.5"><Node label="Corrections" value={typo.learned_corrections_count??0} theme={theme} compact/><Node label="Pending pairs" value={typo.tracked_pending_pairs??0} theme={theme} compact/><Node label="Threshold" value={typo.promotion_threshold??'—'} theme={theme} compact/></div></Rail>
  <Rail title="MEMORY DECAY" subtitle="Unused facts fade" icon={TrendingDown} accent="#64748b" theme={theme}><div className="grid w-full grid-cols-2 gap-1.5"><Node label="Last cycle" value={decay.timestamp?ago(decay.timestamp):'No decay cycle recorded'} theme={theme} compact/><Node label="Weakened" value={decay.decayed_count??0} theme={theme} compact/></div></Rail>
  <Rail title="METACOGNITIVE CALIBRATION" subtitle="Confidence versus correctness" icon={Target} accent="#e24d6b" theme={theme}><div className="grid w-full grid-cols-2 gap-1.5"><Node label="Score" value={calibration.available?(calibration.calibration_score??'—'):'—'} accent="#e24d6b" theme={theme} compact/><Node label="Contradicted" value={calibration.total_contradictions??0} theme={theme} compact/></div></Rail>
  <Rail title="COGNITIVE SELF-AWARENESS" subtitle="Recall, resolution and training signals" icon={Brain} accent="#14b8a6" theme={theme}><Node label="Interactions" value={dep.total_interactions??0} theme={theme}/><Node label="Native rate" value={dep.native_resolution_rate??'—'} accent="#14b8a6" theme={theme}/><Node label="LLM fallback" value={dep.llm_fallback_rate??'—'} theme={theme}/><Node label="Direct recall" value={dep.native_direct_recall_count??0} theme={theme}/><Node label="Identity" value={dep.identity_answer_count??0} theme={theme}/><Node label="Graph multi-hop" value={dep.graph_multi_hop_count??0} theme={theme}/><Node label="SLM assisted" value={dep.slm_assisted_recall_count??0} theme={theme}/><Node label="Contradiction rate" value={state.contradiction_rate??'—'} theme={theme}/><Node label="Training data" value={trainingText} theme={theme} wide/></Rail>
  <Rail title="EVOLUTION & SELF-LEARNING" subtitle="Proposals generated from organism feedback" icon={Network} accent="#a855f7" theme={theme}><Node label="Total proposals" value={evoSummary.total??resources?.evolution?.proposals??0} accent="#a855f7" theme={theme}/><Node label="Approved" value={evoCounts.APPROVED??resources?.evolution?.approved??0} theme={theme}/><Node label="Applied" value={evoCounts.APPLIED??resources?.evolution?.applied??0} theme={theme}/><Node label="Rejected" value={evoCounts.REJECTED??resources?.evolution?.rejected??0} theme={theme}/></Rail>
 </div>;
}
