import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Database, ShieldCheck, Sparkles } from 'lucide-react';
import { AppTheme, LiveStateResponse, SystemResourcesData } from '../types';
import { TabHeader } from './TabHeader';

interface MemoryDBPipelineProps { liveState: LiveStateResponse | null; resources: SystemResourcesData | null; theme?: AppTheme; }
type StageSpec = { title: string; itemName: string; subTag?: string; status: 'REFINED' | 'PRIMARY' | 'SAFE_FALLBACK'; fallbackAttempts: string; };
const STAGE_SPECS: StageSpec[] = [
  { title: 'PIPELINE STAGE 1: PERCEPTION SOURCE', itemName: 'Perception', subTag: 'safe_fallback', status: 'REFINED', fallbackAttempts: 'Attempts Status: primary:fail -> refined:ok' },
  { title: 'PIPELINE STAGE 2: HARDWARE IDENTITY', itemName: 'Hardware_identity', subTag: 'primary', status: 'PRIMARY', fallbackAttempts: 'Attempts Status: primary:ok' },
  { title: 'PIPELINE STAGE 3: RELATIONSHIP GRAPH', itemName: 'Relationship_graph', status: 'SAFE_FALLBACK', fallbackAttempts: 'attempts Status: primary:fail -> refined:fail -> safe_fallback:ok' },
];
function statusClasses(status: StageSpec['status'], isDark: boolean) { if (status === 'PRIMARY') return isDark ? 'bg-emerald-400/10 text-emerald-300 border-emerald-400/20' : 'bg-emerald-50 text-emerald-700 border-emerald-200'; if (status === 'REFINED') return isDark ? 'bg-amber-400/10 text-amber-300 border-amber-400/20' : 'bg-amber-50 text-amber-700 border-amber-200'; return isDark ? 'bg-rose-400/10 text-rose-300 border-rose-400/20' : 'bg-rose-50 text-rose-700 border-rose-200'; }
export const MemoryDBPipeline: React.FC<MemoryDBPipelineProps> = ({ liveState, resources, theme = 'dark' }) => {
  const isDark = theme === 'dark'; const [openStages, setOpenStages] = useState<Record<number, boolean>>({ 0: true, 1: true, 2: true });
  const timestamp = useMemo(() => { const source = liveState?.updated_at || resources?.timestamp; return new Date(source || Date.now()).toLocaleString([], { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }); }, [liveState?.updated_at, resources?.timestamp]);
  const stages = STAGE_SPECS.map((spec, index) => { const extraction = liveState?.extractions?.[index]; const dynamicAttempts = extraction?.attempts?.length ? extraction.attempts.map(a => `${a.stage}:${a.ok ? 'ok' : 'fail'}`).join(' -> ') : null; const dynamicStatus = extraction?.stage_used; const status = dynamicStatus === 'primary' ? 'PRIMARY' : dynamicStatus === 'safe_fallback' ? 'SAFE_FALLBACK' : dynamicStatus === 'refined' ? 'REFINED' : spec.status; return { ...spec, status, itemName: index === 0 ? 'Perception' : index === 1 ? 'Hardware_identity' : 'Relationship_graph', subTag: index === 2 ? undefined : dynamicStatus || spec.subTag, fallbackAttempts: dynamicAttempts ? `Attempts Status: ${dynamicAttempts}` : spec.fallbackAttempts } as StageSpec; });
  const evaluations = resources?.self_evaluation.evaluations ?? 27; const successRate = ((resources?.self_evaluation.success_rate ?? 0.888) * 100).toFixed(1); const knowledgeBuilt = resources?.knowledge.built ?? 9; const knowledgeAccepted = resources?.knowledge.accepted ?? 6; const knowledgePending = resources?.knowledge.pending ?? 2; const evolutionProposals = resources?.evolution.proposals ?? 3; const evolutionApplied = resources?.evolution.applied ?? 0;
  const toggle = (index: number) => setOpenStages(prev => ({ ...prev, [index]: !prev[index] }));
  const headerControls = <><span className="trace-tab-control">DYNAMIC ID: mem-8840</span><span className="trace-tab-control">UPDATED: {timestamp}</span></>;
  return (<section id="card-schema-extractions" className={`trace-root ${isDark ? 'trace-dark' : ''} mx-auto w-full max-w-xl overflow-visible text-xs`}>
    <TabHeader icon={Database} category="JARVIS / MEMORY" title="MEMORY & DB PIPELINE" subtitle="Schema extraction and memory persistence monitor" controls={headerControls} />
    <div className="trace-flow px-3 pb-3 sm:px-3.5"><div className="trace-flow-label text-[10px] font-semibold tracking-wider uppercase"><Database size={12} /> SCHEMA EXTRACTION PIPELINE <span>• LIVE CONTRACT TRACE</span></div>{stages.map((stage, index) => { const isOpen = !!openStages[index]; return (<div className="trace-node" key={stage.title}><div className="trace-node-rail" aria-hidden="true"><div className="trace-node-dot" /></div><article className="trace-stage"><button type="button" onClick={() => toggle(index)} className={`trace-stage-head ${isOpen ? 'is-open' : ''} !flex !items-center !justify-between !w-full !gap-2 min-h-0 py-2`} aria-expanded={isOpen}><div className="flex items-center gap-2 flex-1 min-w-0"><div className="trace-stage-icon shrink-0"><Database size={14} /></div><div className="flex-1 min-w-0"><div className="trace-stage-title text-sm font-bold tracking-tight text-slate-800 dark:text-slate-100 whitespace-normal break-words">{stage.title}</div><div className="trace-stage-summary mt-0.5 text-xs leading-normal break-words">{stage.itemName}</div></div></div><div className="hidden sm:block trace-stage-summary shrink-0 text-[10px]">{stage.subTag || 'schema'}</div><span className={`trace-stage-status shrink-0 px-2 py-1 text-[9px] font-bold tracking-wider ${statusClasses(stage.status, isDark)}`}><span />{stage.status}</span><div className="trace-chevron shrink-0">{isOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</div></button>{isOpen && <div className="trace-stage-body"><div className="trace-stage-content p-2.5"><div className="trace-grid gap-2"><div className="trace-field"><span className="trace-field-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">ITEM NAME</span><span className="trace-field-value text-xs leading-normal break-words">{stage.itemName}</span></div>{stage.subTag && <div className="trace-field"><span className="trace-field-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">SUB-TAG</span><span className="trace-field-value text-[11px] leading-normal break-words">{stage.subTag}</span></div>}<div className="trace-field trace-wide"><span className="trace-field-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">ATTEMPTS STATUS</span><span className="trace-field-value trace-mono text-[11px] leading-normal break-words">{stage.fallbackAttempts}</span></div></div></div></div>}</article></div>);})}<div className="mt-2 text-center font-mono text-[9px] font-bold tracking-[0.12em] text-slate-400">• TRACE END · SUCCESS</div></div>
    <div className="border-t border-slate-200 px-3 py-3.5 dark:border-slate-700/60 sm:px-3.5"><div className="mb-2.5 flex items-center gap-2"><Sparkles className="h-3.5 w-3.5 text-amber-500" /><div><h3 className="font-mono text-sm font-bold tracking-tight text-slate-800 dark:text-slate-100">LEARNING &amp; EVOLUTION SNAPSHOT</h3><p className="mt-0.5 font-mono text-[10px] font-semibold tracking-wider uppercase text-slate-400">Continuous Adaptation</p></div></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><div className="trace-metric p-2.5"><span className="trace-metric-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">EVALUATIONS</span><strong className="text-sm">{evaluations}</strong><div className="mt-0.5 font-mono text-[10px] font-bold text-emerald-600 dark:text-emerald-400">{successRate}% Succ</div></div><div className="trace-metric p-2.5"><span className="trace-metric-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">KNOWLEDGE</span><strong className="text-sm">{knowledgeBuilt} Built</strong><div className="mt-0.5 font-mono text-[10px] text-slate-500 dark:text-slate-400">{knowledgeAccepted} Acc / {knowledgePending} Pend</div></div><div className="trace-metric p-2.5"><span className="trace-metric-label text-[10px] font-semibold tracking-wider uppercase text-slate-400">EVOLUTION</span><strong className="text-sm">{evolutionProposals} Prop</strong><div className="mt-0.5 font-mono text-[10px] text-slate-500 dark:text-slate-400">{evolutionApplied} Applied</div></div></div><div className="trace-callout mt-2.5 p-2.5"><ShieldCheck className="h-3.5 w-3.5 shrink-0" /><div><strong className="text-[10px] font-semibold tracking-wider uppercase">OPERATOR APPROVAL REQUIRED</strong><p className="mt-1 text-[11px] leading-normal">Evolution requires explicit operator approval before runtime application. No autonomous code modification is auto-applied without verification.</p></div></div></div>
  </section>);
};
