import React, { useState, useEffect } from 'react';
import { ChevronDown, ChevronUp, Eye, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { OrganIntrospectionItem, AppTheme } from '../types';
import { api } from '../api/client';
import { TabHeader } from './TabHeader';
interface OrganIntrospectionViewerProps { theme?: AppTheme; }
const QUESTION_LABELS: Record<string, string> = { who_are_you: '1. Who are you?', responsibility: '2. Core Responsibility', received: '3. What was received?', produced: '4. What was produced?', why: '5. Why this decision?', evidence: '6. Grounding Evidence', confidence: '7. Confidence Metric', state_changed: '8. Internal State Changed?', persisted: '9. Persisted to Storage?', unverified: '10. Unverified Claims / Dropped Items' };
export const OrganIntrospectionViewer: React.FC<OrganIntrospectionViewerProps> = ({ theme = 'dark' }) => {
  const isDark = theme === 'dark'; const [organs, setOrgans] = useState<OrganIntrospectionItem[]>([]); const [expandedOrgan, setExpandedOrgan] = useState<string | null>('perception'); const [isLoading, setIsLoading] = useState(false);
  const loadData = async () => { setIsLoading(true); try { const data = await api.getOrganIntrospection(); setOrgans(data); if (data.length > 0 && !expandedOrgan) setExpandedOrgan(data[0].organ_name); } finally { setIsLoading(false); } }; useEffect(() => { loadData(); }, []); const toggleOrgan = (organName: string) => setExpandedOrgan(prev => (prev === organName ? null : organName));
  const headerControls = <><span className="shrink-0 text-[10px] font-mono py-1 px-2 bg-slate-50 border border-slate-200/60 rounded-lg text-slate-700">10 FIXED INQUIRIES</span>{isLoading && <span className="shrink-0 text-[10px] font-mono text-slate-400">LOADING</span>}</>;
  return (<section id="organ-introspection-viewer" className={`trace-root ${isDark ? 'trace-dark' : ''} mx-auto w-full max-w-xl overflow-visible text-xs`}>
    <TabHeader icon={Eye} category="JARVIS / ORGAN" title="ORGAN INSPECTION" controls={headerControls} />
    <div className="trace-flow px-3 pb-3 sm:px-3.5"><div className="trace-flow-label text-[10px] font-semibold tracking-wider uppercase"><Eye size={12} /> INTROSPECTION ACCORDION <span>• 10 FIXED INQUIRIES</span></div><div className="space-y-2">
      {organs.map((organ, organIndex) => { const isExpanded = expandedOrgan === organ.organ_name; return (<article className="trace-stage" key={organ.organ_name}><button type="button" onClick={() => toggleOrgan(organ.organ_name)} className={`trace-stage-head ${isExpanded ? 'is-open' : ''} !flex !items-center !justify-between !w-full !gap-2 min-h-0 py-2`} aria-expanded={isExpanded}><div className="flex items-center gap-2 flex-1 min-w-0"><div className="trace-stage-icon shrink-0"><Eye size={14} /></div><div className="flex-1 min-w-0"><div className="trace-stage-title text-sm font-bold tracking-tight text-slate-800 dark:text-slate-100 whitespace-normal break-words">{organ.displayName}</div><div className="trace-stage-summary mt-0.5 text-[10px] leading-normal break-words">ORGAN QA AUDIT</div></div></div><div className="hidden sm:block trace-stage-summary shrink-0 text-[10px]">{organ.lastTurnId || `ORGAN ${String(organIndex + 1).padStart(2, '0')}`}</div><span className="trace-stage-status shrink-0 px-2 py-1 text-[9px] font-bold tracking-wider whitespace-nowrap"><span />AUDITED</span><div className="trace-chevron shrink-0">{isExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</div></button>{isExpanded && <div className="trace-stage-body"><div className="trace-stage-content p-2.5"><div className="grid grid-cols-1 gap-1.5">{Object.entries(organ.answers).map(([key, value]) => { const label = QUESTION_LABELS[key] || key; const isEvidence = key === 'evidence'; const isUnverified = key === 'unverified'; const isConfidence = key === 'confidence'; return (<div key={key} className={`rounded-xl border border-slate-100 bg-white p-2.5 shadow-sm dark:border-slate-700/70 dark:bg-slate-900/60 ${isEvidence ? 'border-l-2 border-l-brand-400' : ''}`}><div className="mb-1 flex items-center justify-between w-full gap-2"><span className={`flex-1 min-w-0 font-mono text-[10px] font-semibold tracking-wider uppercase break-words ${isEvidence ? 'text-brand-600 dark:text-brand-300' : isConfidence ? 'text-emerald-600 dark:text-emerald-400' : 'text-slate-400'}`}>{label}</span>{isUnverified && <span className="inline-flex shrink-0 items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 font-mono text-[9px] font-bold tracking-wide text-emerald-700 dark:border-emerald-500/20 dark:bg-emerald-500/10 dark:text-emerald-300 whitespace-nowrap"><ShieldCheck className="h-3 w-3" /> Audit Verified</span>}</div><div className="font-mono text-xs leading-normal text-slate-800 dark:text-slate-100 whitespace-pre-wrap break-words">{value}</div>{isConfidence && <div className="mt-1.5 flex items-center gap-1.5 font-mono text-[9px] leading-normal tracking-wide text-emerald-600 dark:text-emerald-400"><CheckCircle2 className="h-3 w-3" /> High-contrast confidence field</div>}</div>); })}</div></div></div>}</article>); })}
    </div><div className="mt-3 text-center font-mono text-[9px] font-bold tracking-[0.12em] text-slate-400">• TRACE END · AUDIT COMPLETE</div></div>
  </section>);
};
